job:
  device: cuda
  type: search
  
random_seed:
  numpy: 0
  python: 0
  torch: 0
  
dataset:
  name: yago3-10
  num_entities: -1
  num_relations: -1
  pickle: false  
  files:
    entity_ids:
      filename: entity_ids.del
      type: map
    relation_ids:
      filename: relation_ids.del
      type: map
    test:
      filename: test.del
      type: triples
    train:
      filename: train.del
      type: triples
    valid:
      filename: valid.del
      type: triples
      
model: complex

train:
  split: train
  type: negative_sampling
  loss: kl
  loss_arg: 1.0
  max_epochs: 400
  batch_size: 1024  
  num_workers: 0  
  optimizer: Adagrad
  optimizer_args:
    +++: +++
  lr_scheduler: ''  
  trace_level: epoch  
  checkpoint:
    every: 0
    keep: 0
  auto_correct: true    
  abort_on_nan: true
  pin_memory: false
  visualize_graph: false

negative_sampling:
  class_name: TrainingJobNegativeSampling
  sampling_type: uniform  
  frequency:
    smoothing: 1  
  num_samples:
    o: -1
    p: 0
    s: 3  
  filtering:
    implementation: fast_if_available
    o: false
    p: false
    s: false
    split: ''  
  shared: true  
  with_replacement: false
  implementation: batch

eval:
  split: valid
  type: entity_ranking
  batch_size: 256
  trace_level: example
  num_workers: 0
  pin_memory: false
  
valid:
  split: valid
  every: 5
  metric: mean_reciprocal_rank_filtered
  metric_expr: float("nan")
  early_stopping:
    patience: 0
    threshold:
      epochs: 0
      metric_value: 0.0  
  trace_level: epoch 
  
entity_ranking:
  class_name: EntityRankingJob
  filter_splits: ['train', 'valid']
  filter_with_test: true
  tie_handling: rounded_mean_rank
  hits_at_k_s: [1, 3, 10, 50, 100, 200, 300, 400, 500, 1000]
  chunk_size: 25000
  metrics_per:
    head_and_tail: false
    relation_type: true
    argument_frequency: false

search:
  type: hyperband_search
  num_workers: 1
  device_pool: []
  on_error: abort

hyperband_search:
  run_id: 'hpb-yago-example'
  host: '127.0.0.2'
  port: "None"
  seed: 2
  num_workers: 1
  max_sh_rounds: 5
  #size_budget_tolerance: 0.0
  epoch_budget_tolerance: [1,1,0,0,0]
  max_epoch_budget: 400
  eta: 4
  variant: 'epochs'
  subsets: 
  - name: ''
    num_entities: 123182
    num_relations: 37
    num_train_triples: 1079040
    num_valid_triples: 5000
  - name: '_7_core'
    num_entities: 62853
    num_relations: 36
    num_train_triples: 792630
    num_valid_triples: 5000
  - name: '_8_core'
    num_entities: 46454
    num_relations: 36
    num_train_triples: 644491
    num_valid_triples: 5000
  - name: '_9_core'
    num_entities: 34147
    num_relations: 36
    num_train_triples: 505130
    num_valid_triples: 5000
  - name: '_10_core'
    num_entities: 22085
    num_relations: 36
    num_train_triples: 352857
    num_valid_triples: 5000
  - name: '_11_core'
    num_entities: 12794
    num_relations: 26
    num_train_triples: 217676
    num_valid_triples: 5000
  - name: '_12_core'
    num_entities: 4117
    num_relations: 21
    num_train_triples: 74304
    num_valid_triples: 5000
  - name: '_13_core'
    num_entities: 884
    num_relations: 11
    num_train_triples: 20122
    num_valid_triples: 5000
  num_hpb_iter: 1
  parameters:
  - bounds:
    - 0.0003
    - 1.0
    log_scale: true
    name: train.optimizer_args.lr
    type: range
  - name: lookup_embedder.initialize
    type: choice
    values:
    - xavier_normal_
    - xavier_uniform_
    - normal_
    - uniform_
  - bounds:
    - 1.0e-05
    - 1.0
    log_scale: true
    name: lookup_embedder.initialize_args.normal_.std
    type: range
  - bounds:
    - -1.0
    - -1.0e-05
    name: lookup_embedder.initialize_args.uniform_.a
    type: range
  - is_ordered: true
    name: lookup_embedder.regularize
    type: choice
    values:
    - ''
    - l3
    - l2
    - l1
  - bounds:
    - 1.0e-20
    - 0.1
    log_scale: true
    name: complex.entity_embedder.regularize_weight
    type: range
  - bounds:
    - 1.0e-20
    - 0.1
    log_scale: true
    name: complex.relation_embedder.regularize_weight
    type: range
  - bounds:
    - -0.5
    - 0.5
    name: complex.entity_embedder.dropout
    type: range
  - bounds:
    - -0.5
    - 0.5
    name: complex.relation_embedder.dropout
    type: range
  - bounds:
    - 1
    - 10000
    log_scale: false
    name: negative_sampling.num_samples.s
    type: range
  - bounds:
    - 1
    - 10000
    log_scale: false
    name: negative_sampling.num_samples.o
    type: range
      

lookup_embedder:
  class_name: LookupEmbedder
  dim: 128
  initialize_args:
    normal_:
      mean: 0.0
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize_args:
    weighted: true
    p: 2
  sparse: true

complex:
  class_name: ComplEx